In [14]:
import numpy as np
from numpy import random

## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [7]:
def funcex1(arr):
    if arr.ndim == 1:
        print(arr)
    else:
        print("Aquest array té més d'una dimensió")

    
array1D = np.array([5,6,9,8,7,4,2,5,6])
funcex1(array1D)

[5 6 9 8 7 4 2 5 6]


## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [37]:
def funcex2(N):
    x=random.randint(100, size=(N,N))
    return x

array = funcex2(3)
print(array)

[[96 80 81]
 [76 91  7]
 [ 1  5 91]]


## Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [41]:
def count_rows_columns(array):
    columns = list(np.sum(array, axis=0))
    rows = list(np.sum(array, axis = 1))
    return (rows, columns)

count_rows_columns(array)

([257, 174, 97], [173, 176, 179])

## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [42]:
def cor(list1, list2):
    mean_l1 = sum(list1)/len(list1)
    mean_l2 = sum(list2)/len(list2)
    cod1 = [x-mean_l1 for x in list1]
    cod2 = [x-mean_l2 for x in list2]
    numerador = sum(np.multiply(cod1,cod2))
    denominador = np.sqrt(sum([x**2 for x in cod1]))*np.sqrt(sum([x**2 for x in cod2]))
    corr = numerador / denominador
    return corr

In [43]:
l1 = [3,4,5,3,4,2,3]
l2 =[10,5,7,9,1,1,1]

cor(l1,l2)

0.1922538386132731