In [4]:
import numpy as np
from numpy import random
import pandas as pd

## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [6]:
def funcex1(arr):
    if arr.ndim == 1:
        print(arr)
        df_describe = pd.DataFrame(arr)
        print(df_describe.describe())
    else:
        print("Aquest array té més d'una dimensió")

    
array1D = np.array([5,6,9,8,7,4,2,5,6])
funcex1(array1D)

[5 6 9 8 7 4 2 5 6]
              0
count  9.000000
mean   5.777778
std    2.108185
min    2.000000
25%    5.000000
50%    6.000000
75%    7.000000
max    9.000000


## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [10]:
def funcex2(N):
    x=random.randint(100, size=(N,N))
    return x

array = funcex2(10)
print(array)

for i in array:
    funcex1(i)

[[14 98 83 28 59 25 46  6 19 67]
 [32 73 26 14 98 15 79 27 16 15]
 [64 34 88 89 64 61 58  6 67 43]
 [59 66 96 85 60 71 97 45 53 81]
 [29 59 80 18  3 73 12 58 74 24]
 [88 37 18 50 12 78 84 88 51 86]
 [63 23 63 21 27 61 80 15 75 41]
 [28 32 59 60 37 38 26 49 73  2]
 [70  9 16 36 76 92 82 74 40 48]
 [61 94 63 20 11 45 21 64 56 69]]
[14 98 83 28 59 25 46  6 19 67]
               0
count  10.000000
mean   44.500000
std    31.231217
min     6.000000
25%    20.500000
50%    37.000000
75%    65.000000
max    98.000000
[32 73 26 14 98 15 79 27 16 15]
              0
count  10.00000
mean   39.50000
std    31.45102
min    14.00000
25%    15.25000
50%    26.50000
75%    62.75000
max    98.00000
[64 34 88 89 64 61 58  6 67 43]
               0
count  10.000000
mean   57.400000
std    24.775436
min     6.000000
25%    46.750000
50%    62.500000
75%    66.250000
max    89.000000
[59 66 96 85 60 71 97 45 53 81]
               0
count  10.000000
mean   71.300000
std    17.907478
min    45.000000
25%   

## Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [11]:
def count_rows_columns(array):
    columns = list(np.sum(array, axis=0))
    rows = list(np.sum(array, axis = 1))
    return (rows, columns)

count_rows_columns(array)

([445, 395, 574, 713, 430, 592, 469, 404, 543, 504],
 [508, 525, 592, 421, 447, 559, 585, 432, 524, 476])

## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.

In [42]:
def cor(list1, list2):
    mean_l1 = sum(list1)/len(list1)
    mean_l2 = sum(list2)/len(list2)
    cod1 = [x-mean_l1 for x in list1]
    cod2 = [x-mean_l2 for x in list2]
    numerador = sum(np.multiply(cod1,cod2))
    denominador = np.sqrt(sum([x**2 for x in cod1]))*np.sqrt(sum([x**2 for x in cod2]))
    corr = numerador / denominador
    return corr

In [43]:
l1 = [3,4,5,3,4,2,3]
l2 = [10,5,7,9,1,1,1]

cor(l1,l2)

0.1922538386132731