In [3]:
import numpy as np
from numpy import random

## Exercici 1
Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [7]:
def funcex1(arr):
    if arr.ndim == 1:
        print(arr)
    else:
        print("Aquest array té més d'una dimensió")

    
array1D = np.array([5,6,9,8,7,4,2,5,6])
funcex1(array1D)

[5 6 9 8 7 4 2 5 6]


## Exercici 2
Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [23]:
def funcex2(N):
    x=random.randint(100, size=(N,N))
    return x

array = funcex2(3)
print(array)

[[ 1 13 16]
 [32 71 76]
 [ 8 59 59]]


## Exercici 3
Crea una funció que donada una taula de dues dimensions (NxM), et calculi els totals per fila i els totals per columna.

In [24]:
print(np.sum(array, axis=0))
    
print(np.sum(array, axis = 1))


[ 41 143 151]
[ 30 179 126]


## Exercici 4
Implementa manualment una funció que calculi el coeficient de correlació. Informa-te'n sobre els seus usos i interpretació.